apps/note/urls.py
# Copyright (C) 2018-2024 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.urls import path

from . import views

app_name = 'note'
urlpatterns = [
    path('transfer/', views.TransactionCreateView.as_view(), name='transfer'),
    path('buttons/create/', views.TransactionTemplateCreateView.as_view(), name='template_create'),
    path('buttons/update/<int:pk>/', views.TransactionTemplateUpdateView.as_view(), name='template_update'),
    path('buttons/', views.TransactionTemplateListView.as_view(), name='template_list'),
    path('consos/', views.ConsoView.as_view(), name='consos'),
    path('transactions/<int:pk>/', views.TransactionSearchView.as_view(), name='transactions'),
]

apps/registration/urls.py
# Copyright (C) 2018-2024 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.urls import path

from . import views

app_name = 'registration'
urlpatterns = [
    path('signup/', views.UserCreateView.as_view(), name="signup"),
    path('validate_email/sent/', views.UserValidationEmailSentView.as_view(), name='email_validation_sent'),
    path('validate_email/resend/<int:pk>/', views.UserResendValidationEmailView.as_view(),
         name='email_validation_resend'),
    path('validate_email/<uidb64>/<token>/', views.UserValidateView.as_view(), name='email_validation'),
    path('validate_user/', views.FutureUserListView.as_view(), name="future_user_list"),
    path('validate_user/<int:pk>/', views.FutureUserDetailView.as_view(), name="future_user_detail"),
    path('validate_user/<int:pk>/invalidate/', views.FutureUserInvalidateView.as_view(), name="future_user_invalidate"),
]

apps/wei/api/urls.py
# Copyright (C) 2018-2024 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from .views import WEIClubViewSet, BusViewSet, BusTeamViewSet, WEIRoleViewSet, WEIRegistrationViewSet, \
    WEIMembershipViewSet


def register_wei_urls(router, path):
    """
    Configure router for Member REST API.
    """
    router.register(path + '/club', WEIClubViewSet)
    router.register(path + '/bus', BusViewSet)
    router.register(path + '/team', BusTeamViewSet)
    router.register(path + '/role', WEIRoleViewSet)
    router.register(path + '/registration', WEIRegistrationViewSet)
    router.register(path + '/membership', WEIMembershipViewSet)

apps/wei/urls.py
# Copyright (C) 2018-2024 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.urls import path

from .views import CurrentWEIDetailView, WEI1AListView, WEIListView, WEICreateView, WEIDetailView, WEIUpdateView, \
    WEIRegistrationsView, WEIMembershipsView, MemberListRenderView, \
    BusCreateView, BusManageView, BusUpdateView, BusTeamCreateView, BusTeamManageView, BusTeamUpdateView, \
    WEIAttributeBus1AView, WEIAttributeBus1ANextView, WEIRegister1AView, WEIRegister2AView, WEIUpdateRegistrationView, \
    WEIDeleteRegistrationView, WEIValidateRegistrationView, WEISurveyView, WEISurveyEndView, WEIClosedView

app_name = 'wei'
urlpatterns = [
    path('detail/', CurrentWEIDetailView.as_view(), name="current_wei_detail"),
    path('list/', WEIListView.as_view(), name="wei_list"),
    path('create/', WEICreateView.as_view(), name="wei_create"),
    path('detail/<int:pk>/', WEIDetailView.as_view(), name="wei_detail"),
    path('update/<int:pk>/', WEIUpdateView.as_view(), name="wei_update"),
    path('detail/<int:pk>/registrations/', WEIRegistrationsView.as_view(), name="wei_registrations"),
    path('detail/<int:pk>/memberships/', WEIMembershipsView.as_view(), name="wei_memberships"),
    path('detail/<int:wei_pk>/memberships/pdf/', MemberListRenderView.as_view(), name="wei_memberships_pdf"),
    path('detail/<int:wei_pk>/memberships/pdf/<int:bus_pk>/', MemberListRenderView.as_view(),
         name="wei_memberships_bus_pdf"),
    path('detail/<int:wei_pk>/memberships/pdf/<int:bus_pk>/<int:team_pk>/', MemberListRenderView.as_view(),
         name="wei_memberships_team_pdf"),
    path('bus-1A/list/<int:pk>/', WEI1AListView.as_view(), name="wei_1A_list"),
    path('add-bus/<int:pk>/', BusCreateView.as_view(), name="add_bus"),
    path('manage-bus/<int:pk>/', BusManageView.as_view(), name="manage_bus"),
    path('update-bus/<int:pk>/', BusUpdateView.as_view(), name="update_bus"),
    path('add-bus-team/<int:pk>/', BusTeamCreateView.as_view(), name="add_team"),
    path('manage-bus-team/<int:pk>/', BusTeamManageView.as_view(), name="manage_bus_team"),
    path('update-bus-team/<int:pk>/', BusTeamUpdateView.as_view(), name="update_bus_team"),
    path('register/<int:wei_pk>/1A/', WEIRegister1AView.as_view(), name="wei_register_1A"),
    path('register/<int:wei_pk>/2A+/', WEIRegister2AView.as_view(), name="wei_register_2A"),
    path('register/<int:wei_pk>/1A/myself/', WEIRegister1AView.as_view(), name="wei_register_1A_myself"),
    path('register/<int:wei_pk>/2A+/myself/', WEIRegister2AView.as_view(), name="wei_register_2A_myself"),
    path('edit-registration/<int:pk>/', WEIUpdateRegistrationView.as_view(), name="wei_update_registration"),
    path('delete-registration/<int:pk>/', WEIDeleteRegistrationView.as_view(), name="wei_delete_registration"),
    path('validate/<int:pk>/', WEIValidateRegistrationView.as_view(), name="validate_registration"),
    path('survey/<int:pk>/', WEISurveyView.as_view(), name="wei_survey"),
    path('survey/<int:pk>/end/', WEISurveyEndView.as_view(), name="wei_survey_end"),
    path('detail/<int:pk>/closed/', WEIClosedView.as_view(), name="wei_closed"),
    path('bus-1A/<int:pk>/', WEIAttributeBus1AView.as_view(), name="wei_bus_1A"),
    path('bus-1A/next/<int:pk>/', WEIAttributeBus1ANextView.as_view(), name="wei_bus_1A_next"),
]

note_kfet/urls.py
# Copyright (C) 2018-2024 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.defaults import bad_request, permission_denied, page_not_found, server_error
from member.views import CustomLoginView

from .admin import admin_site
from .views import IndexView

urlpatterns = [
    # Dev so redirect to something random
    path('', IndexView.as_view(), name='index'),

    # Include project routers
    path('note/', include('note.urls')),
    path('accounts/', include('member.urls')),
    path('registration/', include('registration.urls')),
    path('activity/', include('activity.urls')),
    path('treasury/', include('treasury.urls')),
    path('wei/', include('wei.urls')),

    # Include Django Contrib and Core routers
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin_site.urls, name="admin"),
    path('accounts/login/', CustomLoginView.as_view()),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls')),
    path('permission/', include('permission.urls')),

    # Make coffee
    path('coffee/', include('django_htcpcp_tea.urls')),
]

# During development, serve static and media files
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if "oauth2_provider" in settings.INSTALLED_APPS:
    # OAuth2 provider
    urlpatterns.append(
        path('o/', include('oauth2_provider.urls', namespace='oauth2_provider'))
    )

if "cas_server" in settings.INSTALLED_APPS:
    urlpatterns.append(
        path('cas/', include('cas_server.urls', namespace='cas_server'))
    )

if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


handler400 = bad_request
handler403 = permission_denied

# Only displayed in production, when debug mode is set to False
handler404 = page_not_found
handler500 = server_error

apps/wei/models.py
# Copyright (C) 2018-2024 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

import json
from datetime import date

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField
from member.models import Club, Membership
from note.models import MembershipTransaction
from permission.models import Role


class WEIClub(Club):
    """
    The WEI is a club. Register to the WEI is equivalent than be member of the club.
    """
    year = models.PositiveIntegerField(
        unique=True,
        default=date.today().year,
        verbose_name=_("year"),
    )

    date_start = models.DateField(
        verbose_name=_("date start"),
    )

    date_end = models.DateField(
        verbose_name=_("date end"),
    )

    class Meta:
        verbose_name = _("WEI")
        verbose_name_plural = _("WEI")

    @property
    def is_current_wei(self):
        """
        We consider that this is the current WEI iff there is no future WEI planned.
        """
        return not WEIClub.objects.filter(date_start__gt=self.date_start).exists()

    def update_membership_dates(self):
        """
        We can't join the WEI next years.
        """
        return


class Bus(models.Model):
    """
    The best bus for the best WEI
    """
    wei = models.ForeignKey(
        WEIClub,
        on_delete=models.PROTECT,
        related_name="buses",
        verbose_name=_("WEI"),
    )

    name = models.CharField(
        max_length=255,
        verbose_name=_("name"),
    )

    size = models.IntegerField(
        verbose_name=_("seat count in the bus"),
        default=50,
    )

    description = models.TextField(
        blank=True,
        default="",
        verbose_name=_("description"),
    )

    information_json = models.TextField(
        default="{}",
        verbose_name=_("survey information"),
        help_text=_("Information about the survey for new members, encoded in JSON"),
    )

    class Meta:
        verbose_name = _("Bus")
        verbose_name_plural = _("Buses")
        unique_together = ('wei', 'name',)

    def __str__(self):
        return self.name

    @property
    def information(self):
        """
        The information about the survey for new members are stored in a dictionary that can evolve following the years.
         The dictionary is stored as a JSON string.
        """
        return json.loads(self.information_json)

    @information.setter
    def information(self, information):
        """
        Store information as a JSON string
        """
        self.information_json = json.dumps(information, indent=2)

    @property
    def suggested_first_year(self):
        registrations = WEIRegistration.objects.filter(Q(membership__isnull=True) | Q(membership__bus__isnull=True),
                                                       first_year=True, wei=self.wei)
        registrations = [r for r in registrations if 'selected_bus_pk' in r.information]
        return sum(1 for r in registrations if r.information['selected_bus_pk'] == self.pk)


class BusTeam(models.Model):
    """
    A bus has multiple teams
    """
    bus = models.ForeignKey(
        Bus,
        on_delete=models.CASCADE,
        related_name="teams",
        verbose_name=_("bus"),
    )

    name = models.CharField(
        max_length=255,
        verbose_name=_("name"),
    )

    color = models.PositiveIntegerField(  # Use a color picker to get the hexa code
        verbose_name=_("color"),
        help_text=_("The color of the T-Shirt, stored with its number equivalent"),
    )

    description = models.TextField(
        blank=True,
        default="",
        verbose_name=_("description"),
    )

    class Meta:
        unique_together = ('bus', 'name',)
        verbose_name = _("Bus team")
        verbose_name_plural = _("Bus teams")

    def __str__(self):
        return self.name + " (" + str(self.bus) + ")"


class WEIRole(Role):
    """
    A Role for the WEI can be bus chief, team chief, free electron, ...
    """
    class Meta:
        verbose_name = _("WEI Role")
        verbose_name_plural = _("WEI Roles")


class WEIRegistration(models.Model):
    """
    Store personal data that can be useful for the WEI.
    """
    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="wei",
        verbose_name=_("user"),
    )

    wei = models.ForeignKey(
        WEIClub,
        on_delete=models.PROTECT,
        related_name="users",
        verbose_name=_("WEI"),
    )

    soge_credit = models.BooleanField(
        default=False,
        verbose_name=_("Credit from Société générale"),
    )

    caution_check = models.BooleanField(
        default=False,
        verbose_name=_("Caution check given")
    )

    birth_date = models.DateField(
        verbose_name=_("birth date"),
    )

    gender = models.CharField(
        max_length=16,
        choices=(
            ('male', _("Male")),
            ('female', _("Female")),
            ('nonbinary', _("Non binary")),
        ),
        verbose_name=_("gender"),
    )

    clothing_cut = models.CharField(
        max_length=16,
        choices=(
            ('male', _("Male")),
            ('female', _("Female")),
            ('unisex', _("Unisex")),
        ),
        default='unisex',
        verbose_name=_("clothing cut"),
    )

    clothing_size = models.CharField(
        max_length=4,
        choices=(
            ('XS', "XS"),
            ('S', "S"),
            ('M', "M"),
            ('L', "L"),
            ('XL', "XL"),
            ('XXL', "XXL"),
        ),
        verbose_name=_("clothing size"),
    )

    health_issues = models.TextField(
        blank=True,
        default="",
        verbose_name=_("health issues"),
    )

    emergency_contact_name = models.CharField(
        max_length=255,
        verbose_name=_("emergency contact name"),
        help_text=_("The emergency contact must not be a WEI participant")
    )

    emergency_contact_phone = PhoneNumberField(
        max_length=32,
        verbose_name=_("emergency contact phone"),
    )

    first_year = models.BooleanField(
        default=False,
        verbose_name=_("first year"),
        help_text=_("Tells if the user is new in the school.")
    )

    information_json = models.TextField(
        default="{}",
        verbose_name=_("registration information"),
        help_text=_("Information about the registration (buses for old members, survey for the new members), "
                    "encoded in JSON"),
    )

    class Meta:
        unique_together = ('user', 'wei',)
        verbose_name = _("WEI User")
        verbose_name_plural = _("WEI Users")

    def __str__(self):
        return str(self.user)

    @property
    def information(self):
        """
        The information about the registration (the survey for the new members, the bus for the older members, ...)
        are stored in a dictionary that can evolve following the years. The dictionary is stored as a JSON string.
        """
        return json.loads(self.information_json)

    @information.setter
    def information(self, information):
        """
        Store information as a JSON string
        """
        self.information_json = json.dumps(information, indent=2)

    @property
    def fee(self):
        bde = Club.objects.get(pk=1)
        kfet = Club.objects.get(pk=2)

        kfet_member = Membership.objects.filter(
            club_id=kfet.id,
            user=self.user,
            date_start__gte=kfet.membership_start,
        ).exists()
        bde_member = Membership.objects.filter(
            club_id=bde.id,
            user=self.user,
            date_start__gte=bde.membership_start,
        ).exists()

        fee = self.wei.membership_fee_paid if self.user.profile.paid \
            else self.wei.membership_fee_unpaid
        if not kfet_member:
            fee += kfet.membership_fee_paid if self.user.profile.paid \
                else kfet.membership_fee_unpaid
        if not bde_member:
            fee += bde.membership_fee_paid if self.user.profile.paid \
                else bde.membership_fee_unpaid

        return fee

    @property
    def is_validated(self):
        try:
            return self.membership is not None
        except AttributeError:
            return False


class WEIMembership(Membership):
    bus = models.ForeignKey(
        Bus,
        on_delete=models.PROTECT,
        related_name="memberships",
        null=True,
        default=None,
        verbose_name=_("bus"),
    )

    team = models.ForeignKey(
        BusTeam,
        on_delete=models.PROTECT,
        related_name="memberships",
        null=True,
        blank=True,
        default=None,
        verbose_name=_("team"),
    )

    registration = models.OneToOneField(
        WEIRegistration,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        default=None,
        related_name="membership",
        verbose_name=_("WEI registration"),
    )

    class Meta:
        verbose_name = _("WEI membership")
        verbose_name_plural = _("WEI memberships")

    def make_transaction(self):
        """
        Create Membership transaction associated to this membership.
        """
        if not self.fee or MembershipTransaction.objects.filter(membership=self).exists():
            return

        if self.fee:
            transaction = MembershipTransaction(
                membership=self,
                source=self.user.note,
                destination=self.club.note,
                quantity=1,
                amount=self.fee,
                reason="Adhésion WEI " + self.club.name,
                valid=not self.registration.soge_credit  # Soge transactions are by default invalidated
            )

apps/wei/templates/wei/base.html
{% extends "base.html" %}
{% comment %}
SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load i18n pretty_money perms %}

{# Use a fluid-width container #}
{% block containertype %}container-fluid{% endblock %}

{% block content %}
<div class="row mt-4">
    <div class="col-xl-4">
        {% block profile_info %}
        {% if club %}
        <div class="card bg-light">
            <h4 class="card-header text-center">
                {{ club.name }}
            </h4>
            <div class="card-top text-center">
                <a href="{% url 'member:club_update_pic' club.pk  %}">
                    <img src="{{ club.note.display_image.url }}" class="img-thumbnail mt-2">
                </a>
            </div>
            <div class="card-body" id="profile_infos">
                <dl class="row">
                    <dt class="col-xl-6">{% trans 'name'|capfirst %}</dt>
                    <dd class="col-xl-6">{{ club.name }}</dd>

                    {% if club.require_memberships %}
                    <dt class="col-xl-6">{% trans 'date start'|capfirst %}</dt>
                    <dd class="col-xl-6">{{ club.date_start }}</dd>

                    <dt class="col-xl-6">{% trans 'date end'|capfirst %}</dt>
                    <dd class="col-xl-6">{{ club.date_end }}</dd>

                    <dt class="col-xl-6">{% trans 'year'|capfirst %}</dt>
                    <dd class="col-xl-6">{{ club.year }}</dd>

                    {% if club.membership_fee_paid == club.membership_fee_unpaid %}
                    <dt class="col-xl-6">{% trans 'membership fee'|capfirst %}</dt>
                    <dd class="col-xl-6">{{ club.membership_fee_paid|pretty_money }}</dd>
                    {% else %}
                    {% with bde_kfet_fee=club.parent_club.membership_fee_paid|add:club.parent_club.parent_club.membership_fee_paid %}
                    <dt class="col-xl-6">{% trans 'WEI fee (paid students)'|capfirst %}</dt>
                    <dd class="col-xl-6">{{ club.membership_fee_paid|add:bde_kfet_fee|pretty_money }}
                        <i class="fa fa-question-circle"
                            title="{% trans "The BDE membership is included in the WEI registration." %}"></i></dd>
                    {% endwith %}

                    {% with bde_kfet_fee=club.parent_club.membership_fee_unpaid|add:club.parent_club.parent_club.membership_fee_unpaid %}
                    <dt class="col-xl-6">{% trans 'WEI fee (unpaid students)'|capfirst %}</dt>
                    <dd class="col-xl-6">{{ club.membership_fee_unpaid|add:bde_kfet_fee|pretty_money }}
                        <i class="fa fa-question-circle"
                            title="{% trans "The BDE membership is included in the WEI registration." %}"></i></dd>
                    {% endwith %}
                    {% endif %}
                    {% endif %}

                    {% if "note.view_note"|has_perm:club.note %}
                    <dt class="col-xl-6">{% trans 'balance'|capfirst %}</dt>
                    <dd class="col-xl-6">{{ club.note.balance | pretty_money }}</dd>
                    {% endif %}

                    {% if "note.change_alias"|has_perm:club.note.alias.first %}
                    <dt class="col-xl-4"><a
                            href="{% url 'member:club_alias' club.pk %}">{% trans 'aliases'|capfirst %}</a></dt>
                    <dd class="col-xl-8 text-truncate">{{ club.note.alias.all|join:", " }}</dd>
                    {% endif %}

                    <dt class="col-xl-4">{% trans 'email'|capfirst %}</dt>
                    <dd class="col-xl-8"><a href="mailto:{{ club.email }}">{{ club.email }}</a></dd>
                </dl>
            </div>
            <div class="card-footer text-center">
                {% if True %}
                <a class="btn btn-primary btn-sm my-1" href="{% url 'wei:wei_list' %}"> {% trans "WEI list" %}</a>
                {% endif %}
                {% if club.is_current_wei %}
                {% if can_add_first_year_member %}
                <a class="btn btn-primary btn-sm my-1" href="{% url 'wei:wei_register_1A' wei_pk=club.pk %}"
                    data-turbolinks="false"> {% trans "Register 1A" %}</a>
                {% endif %}
                {% if can_add_any_member %}
                <a class="btn btn-primary btn-sm my-1" href="{% url 'wei:wei_register_2A' wei_pk=club.pk %}"
                    data-turbolinks="false"> {% trans "Register 2A+" %}</a>
                {% endif %}
                {% if "wei.change_"|has_perm:club %}
                <a class="btn btn-primary btn-sm my-1" href="{% url 'wei:wei_update' pk=club.pk %}"
                    data-turbolinks="false"> {% trans "Edit" %}</a>
                {% endif %}
                {% if can_add_bus %}
                <a class="btn btn-primary btn-sm my-1" href="{% url 'wei:add_bus' pk=club.pk %}"
                    data-turbolinks="false"> {% trans "Add bus" %}</a>
                {% endif %}
                {% url 'wei:wei_detail' club.pk as club_detail_url %}
                {%if request.path_info != club_detail_url %}
                <a class="btn btn-primary btn-sm my-1" href="{{ club_detail_url }}">{% trans 'View WEI' %}</a>
                {% endif %}
                {% endif %}
            </div>
        </div>
        {% endif %}
        {% endblock %}
    </div>
    <div class="col-xl-8">
        {% block profile_content %}{% endblock %}
    </div>
</div>
{% endblock %}

apps/wei/templates/wei/busteam_form.html
{% extends "wei/base.html" %}
{% comment %}
SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block profile_content %}
<div class="card bg-light mb-3">
    <h3 class="card-header text-center">
        {{ title }}
    </h3>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-primary" type="submit">{% trans "Submit" %}</button>
        </form>
    </div>
</div>
{% endblock %}

apps/wei/templates/wei/weiclub_detail.html
{% extends "wei/base.html" %}
{% comment %}
SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load render_table from django_tables2 %}
{% load i18n perms %}

{% block profile_content %}
<div class="card bg-white mb-3">
    <div class="card-header text-center">
        <h4>Week-End d'Intégration</h4>
    </div>
    <div class="card-body">
        <p class="lead font-italic">
            Le WEI (Week-End d’Intégration), ou 3 jours d’immersion dans les profondeurs du
            monde post-préparatoire.
        </p>
        <p>
            Que serait une école sans son week-end d’intégration ? Quelques semaines après la
            rentrée, on embarque tous et toutes à bord de bus à thèmes pour quelques jours
            inoubliables dans une destination inconnue. L’objectif de ce week-end : permettre aux
            nouvel·les arrivant·es de se lâcher après 2 ans de dur labeur (voire 3 pour les plus
            chanceux), de découvrir l’ambiance familiale de l’ENS ainsi que de nouer des liens avec
            ceux·elles qu’ils côtoieront par la suite. Dose de chants et de fun garantie !
        </p>
    </div>
    {% if club.is_current_wei %}
    <div class="card-footer text-center">
        {% if not my_registration %}
        {% if not not_first_year %}
        <a class="btn btn-success" href="{% url "wei:wei_register_1A_myself" wei_pk=club.pk %}" data-turbolinks="false">
            {% trans "Register to the WEI! – 1A" %}
        </a>
        {% endif %}
        <a class="btn btn-success" href="{% url "wei:wei_register_2A_myself" wei_pk=club.pk %}" data-turbolinks="false">
            {% trans "Register to the WEI! – 2A+" %}</a>
        {% else %}
        <a class="btn btn-warning" href="{% url "wei:wei_update_registration" pk=my_registration.pk %}"
            data-turbolinks="false">
            {% trans "Update my registration" %}
        </a>
        {% endif %}
    </div>
    {% endif %}
</div>

{% if buses.data %}
<div class="card bg-white mb-3">
    <div class="card-header position-relative" id="clubListHeading">
        <span class="font-weight-bold">
            <i class="fa fa-bus"></i> {% trans "Buses" %}
        </span>
    </div>
    {% render_table buses %}
</div>
{% endif %}

{% if member_list.data %}
<div class="card bg-white mb-3">
    <div class="card-header position-relative" id="clubListHeading">
        <a class="stretched-link font-weight-bold text-decoration-none"
            href="{% url "wei:wei_memberships" pk=club.pk %}">
            <i class="fa fa-users"></i> {% trans "Members of the WEI" %}
        </a>
    </div>
    {% render_table member_list %}
</div>
{% endif %}

{% if history_list.data %}
<div class="card bg-white mb-3">
    <div class="card-header position-relative" id="historyListHeading">
        <a class="stretched-link font-weight-bold text-decoration-none" {% if "note.view_note"|has_perm:club.note %}
            href="{% url 'note:transactions' pk=club.note.pk %}" {% endif %}>
            <i class="fa fa-euro"></i> {% trans "Transaction history" %}
        </a>
    </div>
    <div id="history_list">
        {% render_table history_list %}
    </div>
</div>
{% endif %}

{% if pre_registrations.data %}
<div class="card bg-white mb-3">
    <div class="card-header position-relative" id="historyListHeading">
        <a class="stretched-link font-weight-bold text-decoration-none"
            href="{% url 'wei:wei_registrations' pk=club.pk %}">
            <i class="fa fa-user-plus"></i> {% trans "Unvalidated registrations" %}
        </a>
    </div>
    <div id="history_list">
        {% render_table pre_registrations %}
    </div>
</div>
{% endif %}

    {% if can_validate_1a %}
        <a href="{% url 'wei:wei_1A_list' pk=object.pk %}" class="btn btn-block btn-info">{% trans "Attribute buses" %}</a>
    {% endif %}
{% endblock %}

{% block extrajavascript %}
<script>
    function refreshHistory() {
        $("#history_list").load("{% url 'wei:wei_detail' pk=object.pk %} #history_list");
        $("#profile_infos").load("{% url 'wei:wei_detail' pk=object.pk %} #profile_infos");
    }

    $(document).ready(function () {
        $(".no-perm").parent().addClass("d-none");
        if ($("a[data-type='validate-membership']:not(.d-none)").length === 0) {
            $("a[data-type='validate-membership']").parent().addClass("d-none");
            $("#validate-membership-header").addClass("d-none");
        }
        if ($("a[data-type='delete-membership']:not(.d-none)").length === 0) {
            $("a[data-type='delete-membership']").parent().addClass("d-none");
            $("#delete-membership-header").addClass("d-none");
        }
    });
</script>
{% endblock %}