apps/member/api/urls.py
# Copyright (C) 2018-2024 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from .views import ProfileViewSet, ClubViewSet, MembershipViewSet


def register_members_urls(router, path):
    """
    Configure router for Member REST API.
    """
    router.register(path + '/profile', ProfileViewSet)
    router.register(path + '/club', ClubViewSet)
    router.register(path + '/membership', MembershipViewSet)

apps/member/urls.py
# Copyright (C) 2018-2024 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.urls import path

from . import views

app_name = 'member'
urlpatterns = [
    path('club/', views.ClubListView.as_view(), name="club_list"),
    path('club/create/', views.ClubCreateView.as_view(), name="club_create"),
    path('club/<int:pk>/', views.ClubDetailView.as_view(), name="club_detail"),
    path('club/<int:club_pk>/add_member/', views.ClubAddMemberView.as_view(), name="club_add_member"),
    path('club/manage_roles/<int:pk>/', views.ClubManageRolesView.as_view(), name="club_manage_roles"),
    path('club/renew_membership/<int:pk>/', views.ClubAddMemberView.as_view(), name="club_renew_membership"),
    path('club/<int:pk>/update/', views.ClubUpdateView.as_view(), name="club_update"),
    path('club/<int:pk>/update_pic/', views.ClubPictureUpdateView.as_view(), name="club_update_pic"),
    path('club/<int:pk>/aliases/', views.ClubAliasView.as_view(), name="club_alias"),
    path('club/<int:pk>/members/', views.ClubMembersListView.as_view(), name="club_members"),

    path('user/', views.UserListView.as_view(), name="user_list"),
    path('user/<int:pk>/', views.UserDetailView.as_view(), name="user_detail"),
    path('user/<int:pk>/update/', views.UserUpdateView.as_view(), name="user_update_profile"),
    path('user/<int:pk>/update_pic/', views.ProfilePictureUpdateView.as_view(), name="user_update_pic"),
    path('user/<int:pk>/aliases/', views.ProfileAliasView.as_view(), name="user_alias"),
    path('user/<int:pk>/trust', views.ProfileTrustView.as_view(), name="user_trust"),
    path('manage-auth-token/', views.ManageAuthTokens.as_view(), name='auth_token'),
]

apps/note/urls.py
# Copyright (C) 2018-2024 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.urls import path

from . import views

app_name = 'note'
urlpatterns = [
    path('transfer/', views.TransactionCreateView.as_view(), name='transfer'),
    path('buttons/create/', views.TransactionTemplateCreateView.as_view(), name='template_create'),
    path('buttons/update/<int:pk>/', views.TransactionTemplateUpdateView.as_view(), name='template_update'),
    path('buttons/', views.TransactionTemplateListView.as_view(), name='template_list'),
    path('consos/', views.ConsoView.as_view(), name='consos'),
    path('transactions/<int:pk>/', views.TransactionSearchView.as_view(), name='transactions'),
]

apps/registration/urls.py
# Copyright (C) 2018-2024 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.urls import path

from . import views

app_name = 'registration'
urlpatterns = [
    path('signup/', views.UserCreateView.as_view(), name="signup"),
    path('validate_email/sent/', views.UserValidationEmailSentView.as_view(), name='email_validation_sent'),
    path('validate_email/resend/<int:pk>/', views.UserResendValidationEmailView.as_view(),
         name='email_validation_resend'),
    path('validate_email/<uidb64>/<token>/', views.UserValidateView.as_view(), name='email_validation'),
    path('validate_user/', views.FutureUserListView.as_view(), name="future_user_list"),
    path('validate_user/<int:pk>/', views.FutureUserDetailView.as_view(), name="future_user_detail"),
    path('validate_user/<int:pk>/invalidate/', views.FutureUserInvalidateView.as_view(), name="future_user_invalidate"),
]

note_kfet/urls.py
# Copyright (C) 2018-2024 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.defaults import bad_request, permission_denied, page_not_found, server_error
from member.views import CustomLoginView

from .admin import admin_site
from .views import IndexView

urlpatterns = [
    # Dev so redirect to something random
    path('', IndexView.as_view(), name='index'),

    # Include project routers
    path('note/', include('note.urls')),
    path('accounts/', include('member.urls')),
    path('registration/', include('registration.urls')),
    path('activity/', include('activity.urls')),
    path('treasury/', include('treasury.urls')),
    path('wei/', include('wei.urls')),

    # Include Django Contrib and Core routers
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin_site.urls, name="admin"),
    path('accounts/login/', CustomLoginView.as_view()),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls')),
    path('permission/', include('permission.urls')),

    # Make coffee
    path('coffee/', include('django_htcpcp_tea.urls')),
]

# During development, serve static and media files
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if "oauth2_provider" in settings.INSTALLED_APPS:
    # OAuth2 provider
    urlpatterns.append(
        path('o/', include('oauth2_provider.urls', namespace='oauth2_provider'))
    )

if "cas_server" in settings.INSTALLED_APPS:
    urlpatterns.append(
        path('cas/', include('cas_server.urls', namespace='cas_server'))
    )

if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


handler400 = bad_request
handler403 = permission_denied

# Only displayed in production, when debug mode is set to False
handler404 = page_not_found
handler500 = server_error

apps/member/models.py
# Copyright (C) 2018-2024 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

import datetime
import os

from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models, transaction
from django.db.models import Q
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField
from permission.models import Role
from registration.tokens import email_validation_token
from note.models import MembershipTransaction


class Profile(models.Model):
    """
    An user profile

    We do not want to patch the Django Contrib :model:`auth.User`model;
    so this model add an user profile with additional information.
    """
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    phone_number = PhoneNumberField(
        verbose_name=_('phone number'),
        max_length=50,
        blank=True,
        null=True,
    )

    section = models.CharField(
        verbose_name=_('section'),
        help_text=_('e.g. "1A0", "9A♥", "SAPHIRE"'),
        max_length=255,
        blank=True,
        default="",
    )

    department = models.CharField(
        max_length=8,
        verbose_name=_("department"),
        choices=[
            ('A0', _("Informatics (A0)")),
            ('A1', _("Mathematics (A1)")),
            ('A2', _("Physics (A2)")),
            ("A'2", _("Applied physics (A'2)")),
            ("A''2", _("Chemistry (A''2)")),
            ('A3', _("Biology (A3)")),
            ('B1234', _("SAPHIRE (B1234)")),
            ('B1', _("Mechanics (B1)")),
            ('B2', _("Civil engineering (B2)")),
            ('B3', _("Mechanical engineering (B3)")),
            ('B4', _("EEA (B4)")),
            ('C', _("Design (C)")),
            ('D2', _("Economy-management (D2)")),
            ('D3', _("Social sciences (D3)")),
            ('E', _("English (E)")),
            ('EXT', _("External (EXT)")),
        ]
    )

    promotion = models.PositiveSmallIntegerField(
        null=True,
        default=datetime.date.today().year if datetime.date.today().month >= 8 else datetime.date.today().year - 1,
        verbose_name=_("promotion"),
        help_text=_("Year of entry to the school (None if not ENS student)"),
    )

    address = models.CharField(
        verbose_name=_('address'),
        max_length=255,
        blank=True,
        default="",
    )

    paid = models.BooleanField(
        verbose_name=_("paid"),
        help_text=_("Tells if the user receive a salary."),
        default=False,
    )

    ml_events_registration = models.CharField(
        blank=True,
        default='',
        max_length=2,
        choices=[
            ('', _("No")),
            ('fr', _("Yes (receive them in french)")),
            ('en', _("Yes (receive them in english)")),
        ],
        verbose_name=_("Register on the mailing list to stay informed of the events of the campus (1 mail/week)"),
    )

    ml_sport_registration = models.BooleanField(
        default=False,
        verbose_name=_("Register on the mailing list to stay informed of the sport events of the campus (1 mail/week)"),
    )

    ml_art_registration = models.BooleanField(
        default=False,
        verbose_name=_("Register on the mailing list to stay informed of the art events of the campus (1 mail/week)"),
    )

    report_frequency = models.PositiveSmallIntegerField(
        verbose_name=_("report frequency (in days)"),
        default=0,
    )

    last_report = models.DateTimeField(
        verbose_name=_("last report date"),
        default=timezone.now,
    )

    email_confirmed = models.BooleanField(
        verbose_name=_("email confirmed"),
        default=False,
    )

    registration_valid = models.BooleanField(
        verbose_name=_("registration valid"),
        default=False,
    )

    VSS_charter_read = models.BooleanField(
        verbose_name=_("VSS charter read"),
        default=False
    )

    class Meta:
        verbose_name = _('user profile')
        verbose_name_plural = _('user profile')
        indexes = [models.Index(fields=['user'])]

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('member:user_detail', args=(self.user_id,))

    @property
    def ens_year(self):
        """
        Number of years since the 1st august of the entry year, rounded up.
        """
        if self.promotion is None:
            return 0
        today = datetime.date.today()
        years = today.year - self.promotion
        if today.month >= 8:
            years += 1
        return years

    @property
    def section_generated(self):
        return str(self.ens_year) + self.department

    @property
    def soge(self):
        if "treasury" in settings.INSTALLED_APPS:
            from treasury.models import SogeCredit
            return SogeCredit.objects.filter(user=self.user, credit_transaction__isnull=False).exists()
        return False

    def send_email_validation_link(self):
        subject = "[Note Kfet] " + str(_("Activate your Note Kfet account"))
        token = email_validation_token.make_token(self.user)
        uid = urlsafe_base64_encode(force_bytes(self.user_id))
        message = loader.render_to_string('registration/mails/email_validation_email.txt',
                                          {
                                              'user': self.user,
                                              'domain': os.getenv("NOTE_URL", "note.example.com"),
                                              'token': token,
                                              'uid': uid,
                                          })
        html = loader.render_to_string('registration/mails/email_validation_email.html',
                                       {
                                           'user': self.user,
                                           'domain': os.getenv("NOTE_URL", "note.example.com"),
                                           'token': token,
                                           'uid': uid,
                                       })
        self.user.email_user(subject, message, html_message=html)


class Club(models.Model):
    """
    A club is a group of people, whose membership is handle by their
    :model:`member.Membership`, and gives access to right defined by a :model:`member.Role`.
    """
    name = models.CharField(
        verbose_name=_('name'),
        max_length=255,
        unique=True,
    )

    email = models.EmailField(
        verbose_name=_('email'),
    )

    parent_club = models.ForeignKey(
        'self',
        null=True,
        blank=True,
        on_delete=models.PROTECT,
        verbose_name=_('parent club'),
    )

    # Memberships

    # When set to False, the membership system won't be used.
    # Useful to create notes for activities or departments.
    require_memberships = models.BooleanField(
        default=True,
        verbose_name=_("require memberships"),
        help_text=_("Uncheck if this club don't require memberships."),
    )

    membership_fee_paid = models.PositiveIntegerField(
        default=0,
        verbose_name=_('membership fee (paid students)'),
    )

    membership_fee_unpaid = models.PositiveIntegerField(
        default=0,
        verbose_name=_('membership fee (unpaid students)'),
    )

    membership_duration = models.PositiveIntegerField(
        blank=True,
        null=True,
        verbose_name=_('membership duration'),
        help_text=_('The longest time (in days) a membership can last '
                    '(NULL = infinite).'),
    )

    membership_start = models.DateField(
        blank=True,
        null=True,
        verbose_name=_('membership start'),
        help_text=_('Date from which the members can renew their membership.'),
    )

    membership_end = models.DateField(
        blank=True,
        null=True,
        verbose_name=_('membership end'),
        help_text=_('Maximal date of a membership, after which members must renew it.'),
    )

    class Meta:
        verbose_name = _("club")
        verbose_name_plural = _("clubs")

    def __str__(self):
        return self.name

    @transaction.atomic
    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.require_memberships:
            self.membership_fee_paid = 0
            self.membership_fee_unpaid = 0
            self.membership_duration = None
            self.membership_start = None
            self.membership_end = None
        super().save(force_insert, force_update, update_fields)

    def get_absolute_url(self):
        return reverse_lazy('member:club_detail', args=(self.pk,))

    def update_membership_dates(self):
        """
        This function is called each time the club detail view is displayed.
        Update the year of the membership dates.
        """
        if not self.membership_start or not self.membership_end:
            return

        today = datetime.date.today()

        while (today - self.membership_start).days >= 365:
            if self.membership_start:
                self.membership_start = datetime.date(self.membership_start.year + 1,
                                                      self.membership_start.month, self.membership_start.day)
            if self.membership_end:
                self.membership_end = datetime.date(self.membership_end.year + 1,
                                                    self.membership_end.month, self.membership_end.day)
            self._force_save = True
            self.save(force_update=True)


class Membership(models.Model):

apps/member/templates/member/add_members.html
{% extends "member/base.html" %}
{% comment %}
SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load crispy_forms_tags i18n pretty_money %}

{% block profile_content %}
<div class="card bg-light">
    <h3 class="card-header text-center">
        {{ title }}
    </h3>
    <div class="card-body">
        {% if additional_fee_renewal %}
        <div class="alert alert-warning">
            {% if renewal %}
                {% if club.name == "Kfet" %} {# Auto-renewal #}
                    {% blocktrans trimmed with clubs=clubs_renewal|join:", " pretty_fee=additional_fee_renewal|pretty_money %}
                    The user is not a member of the club·s {{ clubs }}. An additional fee of {{ pretty_fee }}
                    will be charged to renew automatically the membership in this/these club·s.
                    {% endblocktrans %}
                {% else %}
                    {% blocktrans trimmed with clubs=clubs_renewal|join:", " pretty_fee=additional_fee_renewal|pretty_money %}
                        The user is not a member of the club·s {{ clubs }}. Please create the required memberships,
                        otherwise it will fail.
                    {% endblocktrans %}
                {% endif %}
            {% else %}
                {% if club.name == "Kfet" %}
                    {% blocktrans trimmed with clubs=clubs_renewal|join:", " pretty_fee=additional_fee_renewal|pretty_money %}
                    This club has parents {{ clubs }}. An additional fee of {{ pretty_fee }}
                    will be charged to adhere automatically to this/these club·s.
                    {% endblocktrans %}
                {% else %}
                    {% blocktrans trimmed with clubs=clubs_renewal|join:", " pretty_fee=additional_fee_renewal|pretty_money %}
                        This club has parents {{ clubs }}. Please make sure that the user is a member of this or these club·s,
                        otherwise the creation of this membership will fail.
                    {% endblocktrans %}
                {% endif %}
            {% endif %}
        </div>
        {% endif %}

        <form method="post" action="">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-primary" type="submit">{% trans "Submit" %}</button>
        </form>
    </div>
</div>
{% endblock %}

{% block extrajavascript %}
<script>
    function autocompleted(user) {
        $("#id_last_name").val(user.last_name);
        $("#id_first_name").val(user.first_name);
        $.getJSON("/api/members/profile/" + user.id + "/", function (profile) {
            let fee = profile.paid ? "{{ club.membership_fee_paid }}" : "{{ club.membership_fee_unpaid }}";
            $("#id_credit_amount").val((Number(fee) / 100).toFixed(2));
        });
    }

    soge_field = $("#id_soge");

    function fillFields() {
        let checked = soge_field.is(':checked');
        if (!checked) {
            $("input").attr('disabled', false);
            $("#id_user").attr('disabled', true);
            $("select").attr('disabled', false);
            return;
        }

        let credit_type = $("#id_credit_type");
        credit_type.attr('disabled', true);
        credit_type.val(4);

        let credit_amount = $("#id_credit_amount");
        credit_amount.attr('disabled', true);
        credit_amount.val('{{ total_fee }}');

        let bank = $("#id_bank");
        bank.attr('disabled', true);
        bank.val('Société générale');
    }

    soge_field.change(fillFields);
</script>
{% endblock %}

apps/member/templates/member/base.html
{% extends "base.html" %}
{% comment %}
SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load i18n perms %}

{# Use a fluid-width container #}
{% block containertype %}container-fluid{% endblock %}

{% block content %}
<div class="row mt-4">
    <div class="col-xl-4">
        {% block profile_info %}
        <div class="card bg-light" id="card-infos">
            <h4 class="card-header text-center">
                {% if user_object %}
                {% trans "Account #" %}{{ user_object.pk }}
                {% elif club %}
                Club {{ club.name }}
                {% endif %}
            </h4>
            <div class="text-center">
                {% if user_object %}
                <a href="{% url 'member:user_update_pic' user_object.pk  %}">
                    <img src="{{ user_object.note.display_image.url }}" class="img-thumbnail mt-2">
                </a>
                {% elif club %}
                <a href="{% url 'member:club_update_pic' club.pk  %}">
                    <img src="{{ club.note.display_image.url }}" class="img-thumbnail mt-2">
                </a>
                {% endif %}
            </div>
            {% if note.inactivity_reason %}
                <div class="alert alert-danger polymorphic-add-choice">
                    {{ note.get_inactivity_reason_display }}
                </div>
            {% endif %}
            <div class="card-body" id="profile_infos">
                {% if user_object %}
                {% include "member/includes/profile_info.html" %}
                {% elif club %}
                {% include "member/includes/club_info.html" %}
                {% endif %}
            </div>
            <div class="card-footer">
                {% if user_object %}
                <a class="btn btn-sm btn-secondary" href="{% url 'member:user_update_profile' user_object.pk %}">
                    <i class="fa fa-edit"></i> {% trans 'Update Profile' %}
                </a>
                {% url 'member:user_detail' user_object.pk as user_profile_url %}
                {% if request.path_info != user_profile_url %}
                <a class="btn btn-sm btn-primary" href="{{ user_profile_url }}">{% trans 'View Profile' %}</a>
                {% endif %}
                {% elif club and not club.weiclub %}
                {% if can_add_members %}
                <a class="btn btn-sm btn-success" href="{% url 'member:club_add_member' club_pk=club.pk %}"
                   data-turbolinks="false"> {% trans "Add member" %}</a>
                {% endif %}
                {% if ".change_"|has_perm:club %}
                <a class="btn btn-sm btn-secondary" href="{% url 'member:club_update' pk=club.pk %}"
                   data-turbolinks="false">
                    <i class="fa fa-edit"></i> {% trans 'Update Profile' %}
                </a>
                {% endif %}
                {% url 'member:club_detail' club.pk as club_detail_url %}
                {% if request.path_info != club_detail_url %}
                <a class="btn btn-sm btn-primary" href="{{ club_detail_url }}">{% trans 'View Profile' %}</a>
                {% endif %}
                {% endif %}
                {% if can_lock_note %}
                <button class="btn btn-sm btn-danger" data-toggle="modal" data-target="#lock-note-modal">
                    <i class="fa fa-ban"></i> {% trans 'Lock note' %}
                </button>
                {% elif can_unlock_note %}
                <button class="btn btn-sm btn-success" data-toggle="modal" data-target="#unlock-note-modal">
                    <i class="fa fa-check-circle"></i> {% trans 'Unlock note' %}
                </button>
                {% endif %}
            </div>
        </div>
        {% endblock %}
    </div>
    <div class="col-xl-8">
        {% block profile_content %}{% endblock %}
    </div>

    {# Popup to confirm the action of locking the note. Managed by a button #}
    <div class="modal fade" id="lock-note-modal" tabindex="-1" role="dialog" aria-labelledby="lockNote"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="lockNote">{% trans "Lock note" %}</h5>
                    <button type="button" class="close btn-modal" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {% blocktrans trimmed %}
                        Are you sure you want to lock this note? This will prevent any transaction that would be performed,
                        until the note is unlocked.
                    {% endblocktrans %}
                    {% if can_force_lock %}
                    {% blocktrans trimmed %}
                        If you use the force mode, the user won't be able to unlock the note by itself.
                    {% endblocktrans %}
                    {% endif %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary btn-modal" data-dismiss="modal">{% trans "Close" %}</button>
                    {% if can_force_lock %}
                    <button type="button" class="btn btn-danger btn-modal" onclick="lock_note(true, 'forced')">{% trans "Force mode" %}</button>
                    {% endif %}
                    <button type="button" class="btn btn-warning btn-modal" onclick="lock_note(true, 'manual')">{% trans "Lock note" %}</button>
                </div>
            </div>
        </div>
    </div>

    {# Popup to confirm the action of unlocking the note. Managed by a button #}
    <div class="modal fade" id="unlock-note-modal" tabindex="-1" role="dialog" aria-labelledby="unlockNote"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="unlockNote">{% trans "Unlock note" %}</h5>
                    <button type="button" class="close btn-modal" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {% blocktrans trimmed %}
                        Are you sure you want to unlock this note? Transactions will be re-enabled.
                    {% endblocktrans %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary btn-modal" data-dismiss="modal">{% trans "Close" %}</button>
                    <button type="button" class="btn btn-success btn-modal" onclick="lock_note(false, null)">{% trans "Unlock note" %}</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extrajavascript %}
<script>
    function refreshHistory() {
        {% if user_object %}
        $("#history_list").load("{% url 'member:user_detail' pk=user_object.pk %} #history_list");
        $("#profile_infos").load("{% url 'member:user_detail' pk=user_object.pk %} #profile_infos");
        {% else %}
        $("#history_list").load("{% url 'member:club_detail' pk=club.pk %} #history_list");
        $("#profile_infos").load("{% url 'member:club_detail' pk=club.pk %} #profile_infos");
        {% endif %}
    }

    function lock_note(locked, mode) {
        $("button.btn-modal").attr("disabled", "disabled");
        $.ajax({
            url: "/api/note/note/{{ note.pk }}/",
            type: "PATCH",
            dataType: "json",
            headers: {
                "X-CSRFTOKEN": CSRF_TOKEN
            },
            data: {
                is_active: !locked,
                inactivity_reason: mode,
                resourcetype: "{% if user_object %}NoteUser{% else %}NoteClub{% endif %}"
            }
        }).done(function () {
            $("#card-infos").load("#card-infos #card-infos", function () {
                $(".modal").modal("hide");
                $("button.btn-modal").removeAttr("disabled");
            });
        }).fail(function(xhr, textStatus, error) {
            $(".modal").modal("hide");
            $("button.btn-modal").removeAttr("disabled");
            errMsg(xhr.responseJSON);
        });
    }
</script>
{% endblock %}

apps/member/templates/member/club_detail.html
{% extends "member/base.html" %}
{% comment %}
SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load render_table from django_tables2 %}
{% load i18n perms %}

{% block profile_content %}
{% if managers.data %}
<div class="card">
    <div class="card-header position-relative" id="clubListHeading">
        <a class="font-weight-bold">
            <i class="fa fa-users"></i> {% trans "Club managers" %}
        </a>
    </div>
    {% render_table managers %}
</div>

<hr>
{% endif %}

{% if member_list.data %}
<div class="card">
    <div class="card-header position-relative" id="clubListHeading">
        <a class="stretched-link font-weight-bold" href="{% url 'member:club_members' pk=club.pk %}">
            <i class="fa fa-users"></i> {% trans "Club members" %}
        </a>
    </div>
    {% render_table member_list %}
</div>

<hr>
{% endif %}

{% if history_list.data %}
<div class="card">
    <div class="card-header position-relative" id="historyListHeading">
        <a class="stretched-link font-weight-bold" {% if "note.view_note"|has_perm:club.note %}
            href="{% url 'note:transactions' pk=club.note.pk %}" {% endif %}>
            <i class="fa fa-euro"></i> {% trans "Transaction history" %}
        </a>
    </div>
    <div id="history_list">
        {% render_table history_list %}
    </div>
</div>
{% endif %}
{% endblock %}

apps/member/templates/member/club_list.html
{% extends "base_search.html" %}
{% comment %}
SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load i18n perms %}

{% block content %}
{% if can_add_club %}
<a class="btn btn-block btn-success mb-3" href="{% url 'member:club_create' %}" data-turbolinks="false">
    {% trans "Create club" %}
</a>
{% endif %}

{# Search panel #}
{{ block.super }}
{% endblock %}

apps/member/templates/member/profile_detail.html
{% extends "member/base.html" %}
{% comment %}
SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load render_table from django_tables2 %}
{% load i18n perms %}

{% block profile_content %}
{% if not object.profile.email_confirmed and "member.change_profile_email_confirmed"|has_perm:user_object.profile %}
<div class="alert alert-warning">
    {% trans "This user doesn't have confirmed his/her e-mail address." %}
    <a href="{% url "registration:email_validation_resend" pk=user_object.pk %}">
        {% trans "Click here to resend a validation link." %}
    </a>
</div>
{% endif %}

<div class="card bg-light mb-3">
    <div class="card-header position-relative" id="clubListHeading">
        <a class="font-weight-bold">
            <i class="fa fa-users"></i> {% trans "View my memberships" %}
        </a>
    </div>
    {% render_table club_list %}
</div>

<div class="card bg-light">
    <div class="card-header position-relative" id="historyListHeading">
        <a class="stretched-link font-weight-bold text-decoration-none"
            {% if "note.view_note"|has_perm:user_object.note %}
            href="{% url 'note:transactions' pk=user_object.note.pk %}" {% endif %}>
            <i class="fa fa-euro"></i> {% trans "Transaction history" %}
        </a>
    </div>
    <div id="history_list">
        {% render_table history_list %}
    </div>
</div>
{% endblock %}