apps/activity/urls.py
# Copyright (C) 2018-2024 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.urls import path

from . import views

app_name = 'activity'

urlpatterns = [
    path('', views.ActivityListView.as_view(), name='activity_list'),
    path('<int:pk>/', views.ActivityDetailView.as_view(), name='activity_detail'),
    path('<int:pk>/invite/', views.ActivityInviteView.as_view(), name='activity_invite'),
    path('<int:pk>/entry/', views.ActivityEntryView.as_view(), name='activity_entry'),
    path('<int:pk>/update/', views.ActivityUpdateView.as_view(), name='activity_update'),
    path('new/', views.ActivityCreateView.as_view(), name='activity_create'),
    path('calendar.ics', views.CalendarView.as_view(), name='calendar_ics'),
]

apps/note/api/urls.py
# Copyright (C) 2018-2024 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from .views import NotePolymorphicViewSet, AliasViewSet, ConsumerViewSet, \
    TemplateCategoryViewSet, TransactionViewSet, TransactionTemplateViewSet, \
    TrustViewSet


def register_note_urls(router, path):
    """
    Configure router for Note REST API.
    """
    router.register(path + '/note', NotePolymorphicViewSet)
    router.register(path + '/alias', AliasViewSet)
    router.register(path + '/trust', TrustViewSet)
    router.register(path + '/consumer', ConsumerViewSet)

    router.register(path + '/transaction/category', TemplateCategoryViewSet)
    router.register(path + '/transaction/transaction', TransactionViewSet)
    router.register(path + '/transaction/template', TransactionTemplateViewSet)

apps/note/urls.py
# Copyright (C) 2018-2024 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.urls import path

from . import views

app_name = 'note'
urlpatterns = [
    path('transfer/', views.TransactionCreateView.as_view(), name='transfer'),
    path('buttons/create/', views.TransactionTemplateCreateView.as_view(), name='template_create'),
    path('buttons/update/<int:pk>/', views.TransactionTemplateUpdateView.as_view(), name='template_update'),
    path('buttons/', views.TransactionTemplateListView.as_view(), name='template_list'),
    path('consos/', views.ConsoView.as_view(), name='consos'),
    path('transactions/<int:pk>/', views.TransactionSearchView.as_view(), name='transactions'),
]

note_kfet/urls.py
# Copyright (C) 2018-2024 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.defaults import bad_request, permission_denied, page_not_found, server_error
from member.views import CustomLoginView

from .admin import admin_site
from .views import IndexView

urlpatterns = [
    # Dev so redirect to something random
    path('', IndexView.as_view(), name='index'),

    # Include project routers
    path('note/', include('note.urls')),
    path('accounts/', include('member.urls')),
    path('registration/', include('registration.urls')),
    path('activity/', include('activity.urls')),
    path('treasury/', include('treasury.urls')),
    path('wei/', include('wei.urls')),

    # Include Django Contrib and Core routers
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin_site.urls, name="admin"),
    path('accounts/login/', CustomLoginView.as_view()),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls')),
    path('permission/', include('permission.urls')),

    # Make coffee
    path('coffee/', include('django_htcpcp_tea.urls')),
]

# During development, serve static and media files
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if "oauth2_provider" in settings.INSTALLED_APPS:
    # OAuth2 provider
    urlpatterns.append(
        path('o/', include('oauth2_provider.urls', namespace='oauth2_provider'))
    )

if "cas_server" in settings.INSTALLED_APPS:
    urlpatterns.append(
        path('cas/', include('cas_server.urls', namespace='cas_server'))
    )

if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


handler400 = bad_request
handler403 = permission_denied

# Only displayed in production, when debug mode is set to False
handler404 = page_not_found
handler500 = server_error

apps/note/models/transactions.py
# Copyright (C) 2018-2024 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.core.exceptions import ValidationError
from django.db import models, transaction
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from polymorphic.models import PolymorphicModel

from .notes import Note, NoteClub, NoteSpecial
from ..templatetags.pretty_money import pretty_money

"""
Defines transactions
"""


class TemplateCategory(models.Model):
    """
    Defined a recurrent transaction category

    Example: food, softs, ...
    """
    name = models.CharField(
        verbose_name=_("name"),
        max_length=31,
        unique=True,
    )

    class Meta:
        verbose_name = _("transaction category")
        verbose_name_plural = _("transaction categories")

    def __str__(self):
        return str(self.name)


class TransactionTemplate(models.Model):
    """
    Defined a recurrent transaction

    associated to selling something (a burger, a beer, ...)
    """
    name = models.CharField(
        verbose_name=_('name'),
        max_length=255,
        unique=True,
        error_messages={'unique': _("A template with this name already exist")},
    )

    destination = models.ForeignKey(
        NoteClub,
        on_delete=models.PROTECT,
        related_name='+',  # no reverse
        verbose_name=_('destination'),
    )

    amount = models.PositiveIntegerField(
        verbose_name=_('amount'),
    )

    category = models.ForeignKey(
        TemplateCategory,
        on_delete=models.PROTECT,
        related_name='templates',
        verbose_name=_('type'),
        max_length=31,
    )

    display = models.BooleanField(
        default=True,
        verbose_name=_("display"),
    )

    highlighted = models.BooleanField(
        default=False,
        verbose_name=_("highlighted"),
    )

    description = models.CharField(
        verbose_name=_('description'),
        max_length=255,
        blank=True,
    )

    class Meta:
        verbose_name = _("transaction template")
        verbose_name_plural = _("transaction templates")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('note:template_update', args=(self.pk,))


class Transaction(PolymorphicModel):
    """
    General transaction between two :model:`note.Note`

    amount is store in centimes of currency, making it a  positive integer
    value. (from someone to someone else)
    """
    source = models.ForeignKey(
        Note,
        on_delete=models.PROTECT,
        related_name='+',
        verbose_name=_('source'),
    )

    source_alias = models.CharField(
        max_length=255,
        default="",  # Will be remplaced by the name of the note on save
        verbose_name=_('used alias'),
    )

    destination = models.ForeignKey(
        Note,
        on_delete=models.PROTECT,
        related_name='+',
        verbose_name=_('destination'),
    )

    destination_alias = models.CharField(
        max_length=255,
        default="",  # Will be remplaced by the name of the note on save
        verbose_name=_('used alias'),
    )

    created_at = models.DateTimeField(
        verbose_name=_('created at'),
        default=timezone.now,
    )
    quantity = models.PositiveIntegerField(
        verbose_name=_('quantity'),
        default=1,
    )
    amount = models.PositiveIntegerField(
        verbose_name=_('amount'),
    )

    reason = models.CharField(
        verbose_name=_('reason'),
        max_length=255,
    )

    valid = models.BooleanField(
        verbose_name=_('valid'),
        default=True,
    )

    invalidity_reason = models.CharField(
        verbose_name=_('invalidity reason'),
        max_length=255,
        default='',
        blank=True,
    )

    class Meta:
        verbose_name = _("transaction")
        verbose_name_plural = _("transactions")
        indexes = [
            models.Index(fields=['created_at']),
            models.Index(fields=['source']),
            models.Index(fields=['destination']),
        ]

    def __str__(self):
        return self.__class__.__name__ + " from " + str(self.source) + " to " + str(self.destination) + " of "\
            + pretty_money(self.quantity * self.amount) + ("" if self.valid else " invalid")

    @transaction.atomic
    def save(self, *args, **kwargs):
        """
        When saving, also transfer money between two notes
        """
        if self.source.pk == self.destination.pk:
            # When source == destination, no money is transferred and no transaction is created
            return

        self.source = Note.objects.select_for_update().get(pk=self.source_id)
        self.destination = Note.objects.select_for_update().get(pk=self.destination_id)

        # Check that the amounts stay between big integer bounds
        diff_source, diff_dest = self.validate()

        if not (hasattr(self, '_force_save') and self._force_save) \
                and (not self.source.is_active or not self.destination.is_active):
            raise ValidationError(_("The transaction can't be saved since the source note "
                                    "or the destination note is not active."))

        # If the aliases are not entered, we assume that the used alias is the name of the note
        if not self.source_alias:
            self.source_alias = str(self.source)

        if not self.destination_alias:
            self.destination_alias = str(self.destination)

        # We save first the transaction, in case of the user has no right to transfer money
        super().save(*args, **kwargs)

        # Save notes
        self.source.refresh_from_db()
        self.source.balance += diff_source
        self.source._force_save = True
        self.source.save()
        self.destination.refresh_from_db()
        self.destination.balance += diff_dest
        self.destination._force_save = True
        self.destination.save()

    def validate(self):
        previous_source_balance = self.source.balance
        previous_dest_balance = self.destination.balance

        source_balance = previous_source_balance
        dest_balance = previous_dest_balance

        created = self.pk is None
        to_transfer = self.total
        if not created:
            # Revert old transaction
            # We make a select for update to avoid concurrency issues
            old_transaction = Transaction.objects.select_for_update().get(pk=self.pk)
            # Check that nothing important changed
            if not hasattr(self, "_force_save"):
                for field_name in ["source_id", "destination_id", "quantity", "amount"]:
                    if getattr(self, field_name) != getattr(old_transaction, field_name):
                        raise ValidationError(_("You can't update the {field} on a Transaction. "
                                                "Please invalidate it and create one other.").format(field=field_name))

            if old_transaction.valid == self.valid:
                # Don't change anything
                return 0, 0
            if old_transaction.valid:
                source_balance += to_transfer
                dest_balance -= to_transfer

        if self.valid:
            source_balance -= to_transfer
            dest_balance += to_transfer

            # When a transaction is declared valid, we ensure that the invalidity reason is null, if it was
            # previously invalid
            self.invalidity_reason = ""

        if source_balance > 9223372036854775807 or source_balance < -9223372036854775808\
                or dest_balance > 9223372036854775807 or dest_balance < -9223372036854775808:
            raise ValidationError(_("The note balances must be between - 92 233 720 368 547 758.08 € "
                                    "and 92 233 720 368 547 758.07 €."))

        return source_balance - previous_source_balance, dest_balance - previous_dest_balance

    @property
    def total(self):
        return self.amount * self.quantity

    @property
    def type(self):
        return _('Transfer')


class RecurrentTransaction(Transaction):
    """
    Special type of :model:`note.Transaction` associated to a :model:`note.TransactionTemplate`.
    """
    template = models.ForeignKey(
        TransactionTemplate,
        on_delete=models.PROTECT,
    )

    class Meta:
        verbose_name = _("recurrent transaction")
        verbose_name_plural = _("recurrent transactions")

    @transaction.atomic
    def save(self, *args, **kwargs):
        self.clean()
        return super().save(*args, **kwargs)

    def clean(self):
        if self.template.destination != self.destination and not (hasattr(self, '_force_save') and self._force_save):
            raise ValidationError(
                _("The destination of this transaction must equal to the destination of the template."))
        return super().clean()

    @property
    def type(self):
        return _('Template')


class SpecialTransaction(Transaction):
    """
    Special type of :model:`note.Transaction` associated to transactions with special notes
    """
    last_name = models.CharField(
        max_length=255,
        verbose_name=_("name"),
    )

    first_name = models.CharField(
        max_length=255,
        verbose_name=_("first_name"),
    )

    bank = models.CharField(
        max_length=255,
        verbose_name=_("bank"),
        blank=True,
    )

    class Meta:
        verbose_name = _("Special transaction")
        verbose_name_plural = _("Special transactions")

    @transaction.atomic
    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    @property
    def type(self):
        return _('Credit') if isinstance(self.source, NoteSpecial) else _("Debit")

    def is_credit(self):
        return isinstance(self.source, NoteSpecial)

    def is_debit(self):

apps/note/forms.py
# Copyright (C) 2018-2024 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later
from datetime import datetime

from django import forms
from django.contrib.contenttypes.models import ContentType
from django.forms import CheckboxSelectMultiple
from django.utils.timezone import make_aware
from django.utils.translation import gettext_lazy as _
from note_kfet.inputs import Autocomplete, AmountInput, DateTimePickerInput

from .models import TransactionTemplate, NoteClub, Alias


class TransactionTemplateForm(forms.ModelForm):
    class Meta:
        model = TransactionTemplate
        fields = '__all__'

        widgets = {
            'destination':
                Autocomplete(
                    NoteClub,
                    attrs={
                        'api_url': '/api/note/note/',
                        # We don't evaluate the content type at launch because the DB might be not initialized
                        'api_url_suffix':
                            lambda: '&polymorphic_ctype=' + str(ContentType.objects.get_for_model(NoteClub).pk),
                        'placeholder': 'Note ...',
                    },
                ),
            'amount': AmountInput(),
        }


class SearchTransactionForm(forms.Form):
    source = forms.ModelChoiceField(
        queryset=Alias.objects.all(),
        label=_("Source"),
        required=False,
        widget=Autocomplete(
            Alias,
            resetable=True,
            attrs={
                'api_url': '/api/note/alias/',
                'placeholder': 'Note ...',
            },
        ),
    )

    destination = forms.ModelChoiceField(
        queryset=Alias.objects.all(),
        label=_("Destination"),
        required=False,
        widget=Autocomplete(
            Alias,
            resetable=True,
            attrs={
                'api_url': '/api/note/alias/',
                'placeholder': 'Note ...',
            },
        ),
    )

    type = forms.ModelMultipleChoiceField(
        queryset=ContentType.objects.filter(app_label="note", model__endswith="transaction"),
        initial=ContentType.objects.filter(app_label="note", model__endswith="transaction"),
        label=_("Type"),
        required=False,
        widget=CheckboxSelectMultiple(),
    )

    reason = forms.CharField(
        label=_("Reason"),
        required=False,
    )

    valid = forms.BooleanField(
        label=_("Valid"),
        initial=False,
        required=False,
    )

    amount_gte = forms.Field(
        label=_("Total amount greater than"),
        initial=0,
        required=False,
        widget=AmountInput(),
    )

    amount_lte = forms.Field(
        initial=2 ** 31 - 1,
        label=_("Total amount less than"),
        required=False,
        widget=AmountInput(),
    )

    created_after = forms.DateTimeField(
        label=_("Created after"),
        initial=make_aware(datetime(year=2000, month=1, day=1, hour=0, minute=0)),
        required=False,
        widget=DateTimePickerInput(),
    )

    created_before = forms.DateTimeField(
        label=_("Created before"),
        initial=make_aware(datetime(year=2042, month=12, day=31, hour=21, minute=42)),
        required=False,
        widget=DateTimePickerInput(),
    )

apps/note/templates/note/amount_input.html
{% comment %}
SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}

{# Select amount to transfert in € #}
<div class="input-group">
    <input class="form-control mx-auto d-block" type="number" {% if not widget.attrs.negative %}min="0"{% endif %} step="0.01"
           {% if widget.value != None and widget.value != "" %}value="{{ widget.value }}"{% endif %}
           name="{{ widget.name }}"
           {# Other attributes are loaded  #}
           {% for name, value in widget.attrs.items %}
                {% ifnotequal value False %}{{ name }}{% ifnotequal value True %}="{{ value|stringformat:'s' }}"{% endifnotequal %}{% endifnotequal %}
            {% endfor %}>
    <div class="input-group-append">
        <span class="input-group-text">€</span>
    </div>
    <p id="amount-required" class="invalid-feedback"></p>
</div>

apps/note/templates/note/conso_form.html
{% extends "base.html" %}
{% comment %}
SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load i18n static pretty_money django_tables2 %}

{# Use a fluid-width container #}
{% block containertype %}container-fluid{% endblock %}

{% block content %}
    <div class="row mt-4">
        <div class="col-sm-5 col-md-4" id="infos_div">
            <div class="row justify-content-center justify-content-md-end">
                {# User details column #}
                <div class="col picture-col">
                    <div class="card bg-light mb-4 text-center">
                        <a id="profile_pic_link" href="#">
                            <img src="{% static "member/img/default_picture.png" %}"
                                 id="profile_pic" alt="" class="card-img-top d-none d-sm-block">
                        </a>
                        <div class="card-body text-center text-break p-2">
                            <span id="user_note"><i class="small">{% trans "Please select a note" %}</i></span>
                        </div>
                    </div>
                </div>

                {# User selection column #}
                <div class="col-xl" id="user_select_div">
                    <div class="card bg-light border-success mb-4">
                        <div class="card-header">
                            <p class="card-text font-weight-bold">
                                {% trans "Consum" %}
                            </p>
                        </div>
                        <div class="card-body p-0" style="min-height:125px;">
                            <ul class="list-group list-group-flush" id="note_list">
                            </ul>
                        </div>

                        {# User search with autocompletion #}
                        <div class="card-footer">
                            <input class="form-control mx-auto d-block"
                                placeholder="{% trans "Name or alias..." %}" type="text" id="note" autofocus />
                        </div>
                    </div>
                </div>

                {# Summary of consumption and consume button #}
                <div class="col-xl-5 d-none" id="consos_list_div">
                    <div class="card bg-light border-info mb-4">
                        <div class="card-header">
                            <p class="card-text font-weight-bold">
                                {% trans "Select consumptions" %}
                            </p>
                        </div>
                        <div class="card-body p-0" style="min-height:125px;">
                            <ul class="list-group list-group-flush" id="consos_list">
                            </ul>
                        </div>
                        <div class="card-footer text-center">
                            <span id="consume_all" class="btn btn-primary">
                                {% trans "Consume!" %}
                            </span>
                        </div>
                    </div>
                </div>
            </div>

            {# Show last used buttons #}
            <div class="card bg-light mb-4">
                <div class="card-header">
                    <p class="card-text font-weight-bold">
                        {% trans "Highlighted buttons" %}
                    </p>
                </div>
                <div class="card-body text-nowrap" style="overflow:auto hidden">
                    <div class="d-inline-flex flex-wrap justify-content-center" id="highlighted">
                        {% for button in highlighted %}
                            {% if button.display %}
                                <button class="btn btn-outline-dark rounded-0 flex-fill"
                                        id="highlighted_button{{ button.id }}" name="button" value="{{ button.name }}">
                                    {{ button.name }} ({{ button.amount | pretty_money }})
                                </button>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        {# Buttons column #}
        <div class="col">
            {# Regroup buttons under categories #}

            <div class="card bg-light border-primary text-center mb-4">
                {# Tabs for button categories #}
                <div class="card-header">
                    <ul class="nav nav-tabs nav-fill card-header-tabs">
                        {% for category in categories %}
                            <li class="nav-item">
                                <a class="nav-link font-weight-bold" data-toggle="tab" href="#{{ category.name|slugify }}">
                                    {{ category.name }}
                                </a>
                            </li>
                        {% endfor %}
                            <li class="nav-item">
                                <a class="nav-link font-weight-bold" data-toggle="tab" href="#search">
                                    {% trans "Search" %}
                                </a>
                            </li>
                    </ul>
                </div>

                {# Tabs content #}
                <div class="card-body">
                    <div class="tab-content">
                        {% for category in categories %}
                            <div class="tab-pane" id="{{ category.name|slugify }}">
                                <div class="d-inline-flex flex-wrap justify-content-center">
                                    {% for button in category.templates_filtered %}
                                        {% if button.display %}
                                            <button class="btn btn-outline-dark rounded-0 flex-fill"
                                                    id="button{{ button.id }}" name="button" value="{{ button.name }}">
                                                {{ button.name }} ({{ button.amount | pretty_money }})
                                            </button>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            </div>
                        {% endfor %}
                            <div class="tab-pane" id="search">
                                <input class="form-control mx-auto d-block mb-3"
                                       placeholder="{% trans "Search button..." %}" type="search" id="search-input"/>
                                <div class="d-inline-flex flex-wrap justify-content-center" id="search-results">
                                    {% for button in all_buttons %}
                                        {% if button.display %}
                                            <button class="btn btn-outline-dark rounded-0 flex-fill" hidden
                                                    id="search_button{{ button.id }}" name="button" value="{{ button.name }}">
                                                {{ button.name }} ({{ button.amount | pretty_money }})
                                            </button>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            </div>
                    </div>
                </div>

                {# Mode switch #}
                <div class="card-footer border-primary">
                    <a class="btn btn-sm btn-secondary float-left" href="{% url 'note:template_list' %}">
                        <i class="fa fa-edit"></i> {% trans "Edit" %}
                    </a>
                    <div class="btn-group btn-group-toggle float-right" data-toggle="buttons">
                        <label for="single_conso" class="btn btn-sm btn-outline-primary active">
                            <input type="radio" name="conso_type" id="single_conso" checked>
                            <i class="fa fa-long-arrow-left" aria-hidden="true"></i>
                            {% trans "Single consumptions" %}
                        </label>
                        <label for="double_conso" class="btn btn-sm btn-outline-primary">
                            <input type="radio" name="conso_type" id="double_conso">
                            <i class="fa fa-arrows-h" aria-hidden="true"></i>
                            {% trans "Double consumptions" %}
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {# history of transaction #}
    <div class="card shadow mb-4" id="history">
        <div class="card-header">
            <p class="card-text font-weight-bold">
                {% trans "Recent transactions history" %}
            </p>
        </div>
        {% render_table table %}
    </div>
{% endblock %}

{% block extrajavascript %}
    <script type="text/javascript" src="{% static "note/js/consos.js" %}"></script>
    <script type="text/javascript">
        {% for button in highlighted %}
            {% if button.display %}
                document.getElementById("highlighted_button{{ button.id }}").addEventListener("click", function() {
                    addConso({{ button.destination_id }}, {{ button.amount }},
                        {{ polymorphic_ctype }}, {{ button.category_id }}, "{{ button.category.name|escapejs }}",
                        {{ button.id }}, "{{ button.name|escapejs }}");
                });
            {% endif %}
        {% endfor %}

        {% for category in categories %}
            {% for button in category.templates_filtered %}
            {% if button.display %}
                document.getElementById("button{{ button.id }}").addEventListener("click", function() {
                    addConso({{ button.destination_id }}, {{ button.amount }},
                        {{ polymorphic_ctype }}, {{ button.category_id }}, "{{ button.category.name|escapejs }}",
                        {{ button.id }}, "{{ button.name|escapejs }}");
                });
            {% endif %}
            {% endfor %}
        {% endfor %}

        {% for button in all_buttons %}
            {% if button.display %}
                document.getElementById("search_button{{ button.id }}").addEventListener("click", function() {
                    addConso({{ button.destination_id }}, {{ button.amount }},
                        {{ polymorphic_ctype }}, {{ button.category_id }}, "{{ button.category.name|escapejs }}",
                        {{ button.id }}, "{{ button.name|escapejs }}");
                });
            {% endif %}
        {% endfor %}
    </script>
{% endblock %}

apps/note/templates/note/search_transactions.html
{% extends "base.html" %}
{% comment %}
SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load render_table from django_tables2 %}
{% load crispy_forms_tags %}

{# Use a fluid-width container #}
{% block containertype %}container-fluid{% endblock %}

{% block content %}
<div class="row mt-4">
    <div class="col-xl-4">
        <div class="card bg-light mb-3">
            <h3 class="card-header text-center">
                {{ title }}
            </h3>
            <div class="card-body">
                {% crispy form %}
            </div>
        </div>
    </div>
    <div class="col-xl-8">
        <div class="card bg-light">
            <div id="table">
                {% render_table table %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extrajavascript %}
<script>
    function refreshHistory() {
        $("#history_list").load("{% url 'note:transactions' pk=object.pk %} #history_list");
        $("#profile_infos").load("{% url 'note:transactions' pk=object.pk %} #profile_infos");
    }

    function refreshFilters() {
        let filters = "";
        filters += "source=" + $("#id_source_pk").val();
        filters += "&destination=" + $("#id_destination_pk").val();
        filters += $("input[name='type']:checked").map(function () {
            return "&type=" + $(this).val();
        }).toArray().join("");
        filters += "&reason=" + $("#id_reason").val();
        filters += "&valid=" + ($("#id_valid").is(":checked") ? "1" : "");
        filters += "&amount_gte=" + $("#id_amount_gte").val();
        filters += "&amount_lte=" + $("#id_amount_lte").val();
        filters += "&created_after=" + $("#id_created_after").val();
        filters += "&created_before=" + $("#id_created_before").val();
        console.log(filters.replace(" ", "%20"));
        $("#table").load(location.pathname + "?" + filters.replaceAll(" ", "%20") + " #table");
    }

    function autocompleted() {
        refreshFilters();
    }

    $(document).ready(function () {
        $("input").change(refreshFilters);
        $("input").keyup(refreshFilters);
    });
</script>
{% endblock %}